[project]
name = "news-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.4.1",
    "fastmcp>=2.14.3",
    "gnews>=0.4.3",
    "sentence-transformers>=5.2.0",
]
